name: 'lakehouse'
version: '1.0.0'
profile: 'lakehouse'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS iceberg.bronze WITH (location = 's3a://stocks/bronze/')"
  - "CREATE SCHEMA IF NOT EXISTS iceberg.silver WITH (location = 's3a://stocks/silver/')"
  - "CREATE SCHEMA IF NOT EXISTS iceberg.gold WITH (location = 's3a://stocks/gold/')"
  - "CREATE SCHEMA IF NOT EXISTS iceberg.decision WITH (location = 's3a://stocks/decision/')"

seeds:
  lakehouse:
    +schema: decision
    knowledge_rules:
      +column_types:
        certainty_factor: double
        is_active: boolean
    decision_table:
      +column_types: {}

models:
  lakehouse:
    silver:
      +materialized: incremental
      +schema: silver
    gold:
      +materialized: incremental
      +schema: gold
    decision:
      +materialized: incremental
      +schema: decision
