lakehouse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: "{{ env_var('TRINO_USER', 'iceberg') }}"
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      catalog: iceberg
      schema: silver
      threads: 4
      session_properties:
        query_max_run_time: "2h"

    dev_local:
      type: trino
      method: none
      user: "{{ env_var('TRINO_USER', 'iceberg') }}"
      host: localhost
      port: 8080
      catalog: iceberg
      schema: silver
      threads: 4
