# Nessie Iceberg REST catalog — warehouse + MinIO access
nessie.catalog.default-warehouse=stocks
nessie.catalog.warehouses.stocks.location=s3://stocks/
nessie.catalog.service.s3.default-options.path-style-access=true
nessie.catalog.service.s3.default-options.endpoint=http://minio:9000
nessie.catalog.service.s3.default-options.region=eu-south-1
nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:minio-creds
minio-creds.name=admin
minio-creds.secret=password
